FROM shaot666/nginx-wget:0.0.1
MAINTAINER shaot <aoshaot@163.com>
RUN wget https://github.com/alibaba/canal/releases/download/canal-1.1.5-alpha-2/canal.admin-1.1.5-SNAPSHOT.tar.gz && \ 
    wget https://github.com/alibaba/canal/releases/download/canal-1.1.5-alpha-2/canal.example-1.1.5-SNAPSHOT.tar.gz

