FROM rstarmer/nginx-curl
MAINTAINER shaot <aoshaot@163.com>
RUN curl -O https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.18.0/crictl-v1.18.0-linux-amd64.tar.gz  && \ 
	curl -O https://github.com/projectcalico/calicoctl/releases/download/v3.16.0/calicoctl-linux-amd64 && \ 
	curl -O https://github.com/containernetworking/plugins/releases/download/v0.8.7/cni-plugins-linux-amd64-v0.8.7.tgz
